// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzRsjpYM-Cez8oM6vx7AtnN6msgmnc7o4',
    appId: '1:924611545859:web:115fc261b3f574d440f736',
    messagingSenderId: '924611545859',
    projectId: 'social-media-feed-app-ce6c5',
    authDomain: 'social-media-feed-app-ce6c5.firebaseapp.com',
    storageBucket: 'social-media-feed-app-ce6c5.firebasestorage.app',
    measurementId: 'G-D3QT2QRYP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoW5kGGZ1uOZucIXk86WmTSsGwqyp7XZg',
    appId: '1:924611545859:android:8769d7331c70633040f736',
    messagingSenderId: '924611545859',
    projectId: 'social-media-feed-app-ce6c5',
    storageBucket: 'social-media-feed-app-ce6c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ9Fk0qk3ss46kv7Owcrtbpqegtzncs5A',
    appId: '1:924611545859:ios:d1a069038f2c092140f736',
    messagingSenderId: '924611545859',
    projectId: 'social-media-feed-app-ce6c5',
    storageBucket: 'social-media-feed-app-ce6c5.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaFeedApp',
  );
}
